//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private bool BoolValueField;
    
    private string StringValueField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool BoolValue
    {
        get
        {
            return this.BoolValueField;
        }
        set
        {
            this.BoolValueField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string StringValue
    {
        get
        {
            return this.StringValueField;
        }
        set
        {
            this.StringValueField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRouting")]
public interface IRouting
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetData", ReplyAction="http://tempuri.org/IRouting/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetData", ReplyAction="http://tempuri.org/IRouting/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRouting/GetDataUsingDataContractResponse")]
    CompositeType GetDataUsingDataContract(CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRouting/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetAllStations", ReplyAction="http://tempuri.org/IRouting/GetAllStationsResponse")]
    LetsGoBiking_tc.Lib2.Models.Station[] GetAllStations();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetAllStations", ReplyAction="http://tempuri.org/IRouting/GetAllStationsResponse")]
    System.Threading.Tasks.Task<LetsGoBiking_tc.Lib2.Models.Station[]> GetAllStationsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetStation", ReplyAction="http://tempuri.org/IRouting/GetStationResponse")]
    LetsGoBiking_tc.Lib2.Models.Station GetStation(string city, string stationNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouting/GetStation", ReplyAction="http://tempuri.org/IRouting/GetStationResponse")]
    System.Threading.Tasks.Task<LetsGoBiking_tc.Lib2.Models.Station> GetStationAsync(string city, string stationNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRoutingChannel : IRouting, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RoutingClient : System.ServiceModel.ClientBase<IRouting>, IRouting
{
    
    public RoutingClient()
    {
    }
    
    public RoutingClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RoutingClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RoutingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RoutingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }
    
    public CompositeType GetDataUsingDataContract(CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.Threading.Tasks.Task<CompositeType> GetDataUsingDataContractAsync(CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
    
    public LetsGoBiking_tc.Lib2.Models.Station[] GetAllStations()
    {
        return base.Channel.GetAllStations();
    }
    
    public System.Threading.Tasks.Task<LetsGoBiking_tc.Lib2.Models.Station[]> GetAllStationsAsync()
    {
        return base.Channel.GetAllStationsAsync();
    }
    
    public LetsGoBiking_tc.Lib2.Models.Station GetStation(string city, string stationNumber)
    {
        return base.Channel.GetStation(city, stationNumber);
    }
    
    public System.Threading.Tasks.Task<LetsGoBiking_tc.Lib2.Models.Station> GetStationAsync(string city, string stationNumber)
    {
        return base.Channel.GetStationAsync(city, stationNumber);
    }
}
namespace LetsGoBiking_tc.Lib2.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/LetsGoBiking_tc.Lib2.Models")]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string addressField;
        
        private bool bankingField;
        
        private bool bonusField;
        
        private bool connectedField;
        
        private string contractNameField;
        
        private System.DateTime lastUpdateField;
        
        private LetsGoBiking_tc.Lib2.Models.MainStands mainStandsField;
        
        private string nameField;
        
        private int numberField;
        
        private bool overflowField;
        
        private string overflowStandsField;
        
        private LetsGoBiking_tc.Lib2.Models.Position positionField;
        
        private string shapeField;
        
        private string statusField;
        
        private LetsGoBiking_tc.Lib2.Models.TotalStands totalStandsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool banking
        {
            get
            {
                return this.bankingField;
            }
            set
            {
                this.bankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool connected
        {
            get
            {
                return this.connectedField;
            }
            set
            {
                this.connectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractName
        {
            get
            {
                return this.contractNameField;
            }
            set
            {
                this.contractNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastUpdate
        {
            get
            {
                return this.lastUpdateField;
            }
            set
            {
                this.lastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetsGoBiking_tc.Lib2.Models.MainStands mainStands
        {
            get
            {
                return this.mainStandsField;
            }
            set
            {
                this.mainStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool overflow
        {
            get
            {
                return this.overflowField;
            }
            set
            {
                this.overflowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string overflowStands
        {
            get
            {
                return this.overflowStandsField;
            }
            set
            {
                this.overflowStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetsGoBiking_tc.Lib2.Models.Position position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shape
        {
            get
            {
                return this.shapeField;
            }
            set
            {
                this.shapeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetsGoBiking_tc.Lib2.Models.TotalStands totalStands
        {
            get
            {
                return this.totalStandsField;
            }
            set
            {
                this.totalStandsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainStands", Namespace="http://schemas.datacontract.org/2004/07/LetsGoBiking_tc.Lib2.Models")]
    public partial class MainStands : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LetsGoBiking_tc.Lib2.Models.Availabilities availabilitiesField;
        
        private int capacityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetsGoBiking_tc.Lib2.Models.Availabilities availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/LetsGoBiking_tc.Lib2.Models")]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalStands", Namespace="http://schemas.datacontract.org/2004/07/LetsGoBiking_tc.Lib2.Models")]
    public partial class TotalStands : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LetsGoBiking_tc.Lib2.Models.Availabilities availabilitiesField;
        
        private int capacityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LetsGoBiking_tc.Lib2.Models.Availabilities availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Availabilities", Namespace="http://schemas.datacontract.org/2004/07/LetsGoBiking_tc.Lib2.Models")]
    public partial class Availabilities : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int bikesField;
        
        private int electricalBikesField;
        
        private int electricalInternalBatteryBikesField;
        
        private int electricalRemovableBatteryBikesField;
        
        private int mechanicalBikesField;
        
        private int standsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bikes
        {
            get
            {
                return this.bikesField;
            }
            set
            {
                this.bikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalBikes
        {
            get
            {
                return this.electricalBikesField;
            }
            set
            {
                this.electricalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalInternalBatteryBikes
        {
            get
            {
                return this.electricalInternalBatteryBikesField;
            }
            set
            {
                this.electricalInternalBatteryBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalRemovableBatteryBikes
        {
            get
            {
                return this.electricalRemovableBatteryBikesField;
            }
            set
            {
                this.electricalRemovableBatteryBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mechanicalBikes
        {
            get
            {
                return this.mechanicalBikesField;
            }
            set
            {
                this.mechanicalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stands
        {
            get
            {
                return this.standsField;
            }
            set
            {
                this.standsField = value;
            }
        }
    }
}
